# Generated by Django 5.0.6 on 2024-06-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateTimeField()),
                ('melhor_de', models.IntegerField()),
                ('numero_da_mesa', models.IntegerField()),
                ('tempo_total', models.DurationField()),
                ('jogador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_jogador1', to='operacao.jogador')),
                ('jogador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_jogador2', to='operacao.jogador')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='operacao.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.IntegerField()),
                ('pontos_jogador1', models.IntegerField()),
                ('pontos_jogador2', models.IntegerField()),
                ('faltas_jogador1', models.IntegerField()),
                ('faltas_jogador2', models.IntegerField()),
                ('tempo_pontos_jogador1', models.DurationField()),
                ('tempo_pontos_jogador2', models.DurationField()),
                ('tempo_faltas_jogador1', models.DurationField()),
                ('tempo_faltas_jogador2', models.DurationField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='operacao.partida')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets_vencidos', to='operacao.jogador')),
            ],
        ),
    ]
