# Generated by Django 5.0.6 on 2024-06-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_alter_jogador_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_partida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
