# Generated by Django 5.0.6 on 2024-06-10 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0004_partida_tempo_inicio_alter_partida_tempo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='tempo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
