# Generated by Django 5.0.6 on 2024-06-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0005_alter_partida_tempo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='faltas_jogador1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='faltas_jogador2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='pontos_jogador1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='pontos_jogador2',
            field=models.IntegerField(default=0),
        ),
    ]
