# Generated by Django 5.0.6 on 2024-06-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0006_alter_set_faltas_jogador1_alter_set_faltas_jogador2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='tempo_faltas_jogador1',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='tempo_faltas_jogador2',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='tempo_pontos_jogador1',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='tempo_pontos_jogador2',
            field=models.DurationField(null=True),
        ),
    ]
