# Generated by Django 5.0.6 on 2024-07-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0008_actionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('link_transmissao', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
