# Generated by Django 5.0.6 on 2024-07-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0009_mesa_remove_partida_numero_da_mesa_partida_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='numero_da_mesa',
        ),
        migrations.AddField(
            model_name='partida',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='operacao.mesa'),
            preserve_default=False,
        ),
    ]
