# Generated by Django 5.0.6 on 2024-07-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0010_remove_partida_numero_da_mesa_partida_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='partida_atual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_atual', to='operacao.partida'),
        ),
    ]
