# Generated by Django 5.0.6 on 2024-07-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0011_mesa_partida_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='numero',
        ),
    ]
