# Generated by Django 5.0.6 on 2024-07-25 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0012_remove_mesa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='tempo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
