# Generated by Django 5.0.6 on 2024-07-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0013_alter_partida_tempo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='operacao.mesa'),
        ),
    ]
