# Generated by Django 5.0.6 on 2024-07-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0014_alter_partida_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='tempo_total',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
