# Generated by Django 5.0.6 on 2024-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0015_alter_partida_tempo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='link_transmissao',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
