# Generated by Django 5.0.6 on 2024-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0016_alter_mesa_link_transmissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
