# Generated by Django 5.0.6 on 2024-08-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0018_alter_partida_data_partida_alter_partida_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='tacada',
            field=models.IntegerField(null=True),
        ),
    ]
